using NumericWordsConversion;

using PrimeOrdersLibrary.Data.Common;

using Syncfusion.Drawing;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;

namespace PrimeOrdersLibrary.Exporting;

internal static class PDFExportUtil
{
	// Shared color constants
	internal static readonly Color _primaryColor = Color.FromArgb(81, 43, 212);
	internal static readonly Color _secondaryColor = Color.FromArgb(104, 33, 122);
	internal static readonly Color _accentColor = Color.FromArgb(0, 164, 239);
	internal static readonly Color _lightGray = Color.FromArgb(245, 245, 245);
	internal static readonly Color _darkGray = Color.FromArgb(64, 64, 64);

	// Shared font constants
	internal static readonly PdfStandardFont _titleFont = new(PdfFontFamily.Helvetica, 24, PdfFontStyle.Bold);
	internal static readonly PdfStandardFont _headerFont = new(PdfFontFamily.Helvetica, 16, PdfFontStyle.Bold);
	internal static readonly PdfStandardFont _subHeaderFont = new(PdfFontFamily.Helvetica, 12, PdfFontStyle.Bold);
	internal static readonly PdfStandardFont _normalFont = new(PdfFontFamily.Helvetica, 10);
	internal static readonly PdfStandardFont _boldFont = new(PdfFontFamily.Helvetica, 10, PdfFontStyle.Bold);
	internal static readonly PdfStandardFont _smallFont = new(PdfFontFamily.Helvetica, 8);

	internal const float _pageMargin = 20f;

	/// <summary>
	/// Creates a common PDF document header with customizable title
	/// </summary>
	internal static PdfPageTemplateElement CreateHeader(PdfDocument doc, string headerTitle)
	{
		var headerRect = new RectangleF(0, 0, doc.Pages[0].GetClientSize().Width, 50);

		PdfPageTemplateElement header = new(headerRect);
		header.Graphics.DrawRectangle(new PdfSolidBrush(_primaryColor), headerRect);

		PdfStringFormat format = new()
		{
			Alignment = PdfTextAlignment.Center,
			LineAlignment = PdfVerticalAlignment.Middle
		};

		header.Graphics.DrawString(headerTitle, _titleFont, PdfBrushes.White,
			new PointF(headerRect.Width / 2, headerRect.Height / 2), format);

		return header;
	}

	/// <summary>
	/// Creates a common PDF document footer with timestamp and pagination
	/// </summary>
	internal static PdfPageTemplateElement CreateFooter(PdfDocument doc)
	{
		RectangleF rect = new(0, 0, doc.Pages[0].GetClientSize().Width, 10);

		PdfPageTemplateElement footer = new(rect);
		PdfPageNumberField pageNumber = new(_smallFont, new PdfSolidBrush(_darkGray));
		PdfPageCountField count = new(_smallFont, new PdfSolidBrush(_darkGray));

		string prefix = "Generated By ";
		string suffix = $" | Page {{0}} of {{1}} | Printed on: {DateTime.Now:dddd, MMMM dd, yyyy hh:mm tt}";

		PdfCompositeField compositeField = new()
		{
			Text = prefix + "https://aadisoft.vercel.app" + suffix,
			AutomaticFields = [pageNumber, count],
			Font = _smallFont,
			Brush = new PdfSolidBrush(_darkGray),
			Bounds = footer.Bounds,
			StringFormat = new()
			{
				Alignment = PdfTextAlignment.Center,
				LineAlignment = PdfVerticalAlignment.Middle
			}
		};

		compositeField.Draw(footer.Graphics);
		return footer;
	}

	/// <summary>
	/// Draws common company information section
	/// </summary>
	internal static float DrawCompanyInformation(PdfPage pdfPage, string invoiceType)
	{
		RectangleF detailsRect = new(20, 10, pdfPage.GetClientSize().Width - 40, 80);
		pdfPage.Graphics.DrawRectangle(new PdfPen(_lightGray, 1), new PdfSolidBrush(_lightGray), detailsRect);

		pdfPage.Graphics.DrawString("Salasar Foods Guwahati", _normalFont, new PdfSolidBrush(_darkGray), new PointF(30, detailsRect.Y + 10));
		pdfPage.Graphics.DrawString("GST NO: XXXXXXX", _normalFont, new PdfSolidBrush(_darkGray), new PointF(30, detailsRect.Y + 25));
		pdfPage.Graphics.DrawString("Mobile No: XXXXXX", _normalFont, new PdfSolidBrush(_darkGray), new PointF(30, detailsRect.Y + 40));
		pdfPage.Graphics.DrawString("Email: info@primeorders.com", _normalFont, new PdfSolidBrush(_darkGray), new PointF(30, detailsRect.Y + 55));

		var invoiceTitleSize = _headerFont.MeasureString(invoiceType);
		pdfPage.Graphics.DrawString(invoiceType, _headerFont, new PdfSolidBrush(_secondaryColor), new PointF(pdfPage.GetClientSize().Width - invoiceTitleSize.Width - 30, detailsRect.Y + 30));

		return detailsRect.Height + detailsRect.Y + 20;
	}

	/// <summary>
	/// Creates and configures a PDF grid with common styling
	/// </summary>
	internal static PdfGrid CreateStyledGrid<T>(IEnumerable<T> dataSource, float[] columnWidths, PdfTextAlignment[] columnAlignments)
	{
		PdfGrid pdfGrid = new()
		{
			DataSource = dataSource.ToList()
		};

		// Set column widths
		for (int i = 0; i < columnWidths.Length && i < pdfGrid.Columns.Count; i++)
			pdfGrid.Columns[i].Width = columnWidths[i];

		// Apply header styling
		pdfGrid.Headers.ApplyStyle(new PdfGridCellStyle
		{
			Font = _boldFont,
			TextBrush = PdfBrushes.White,
			CellPadding = new PdfPaddings(5, 5, 5, 5),
			BackgroundBrush = new PdfSolidBrush(_primaryColor),
			Borders = new PdfBorders { All = new PdfPen(Color.Black, 0.5f) }
		});

		// Apply alternating row colors
		int index = 0;
		foreach (var row in pdfGrid.Rows)
		{
			index++;
			if (index % 2 == 0)
				row.Style.BackgroundBrush = new PdfSolidBrush(_lightGray);
			else
				row.Style.BackgroundBrush = new PdfSolidBrush(Color.White);
		}

		// Apply grid styling
		pdfGrid.Style = new()
		{
			Font = _normalFont,
			TextBrush = PdfBrushes.Black,
			CellPadding = new PdfPaddings(5, 5, 5, 5),
		};

		// Set column alignments
		for (int i = 0; i < columnAlignments.Length && i < pdfGrid.Columns.Count; i++)
			pdfGrid.Columns[i].Format = new(columnAlignments[i], PdfVerticalAlignment.Middle);

		return pdfGrid;
	}

	/// <summary>
	/// Draws a summary section with financial totals
	/// </summary>
	internal static float DrawSummarySection(PdfDocument pdfDocument, PdfPage pdfPage, float currentY,
		Dictionary<string, string> summaryItems, decimal grandTotal, string additionalInfo = null)
	{
		// Check if page has space for summary
		if (currentY + 250 > pdfPage.GetClientSize().Height - _pageMargin)
		{
			pdfDocument.Pages.Add();
			pdfPage = pdfDocument.Pages[pdfDocument.Pages.Count - 1];
			currentY = _pageMargin;
		}

		var summaryWidth = 250f;
		var summaryX = pdfPage.GetClientSize().Width - summaryWidth - 20;
		var summaryHeight = 250f;

		var summaryRect = new RectangleF(summaryX, currentY, summaryWidth, summaryHeight);
		pdfPage.Graphics.DrawRectangle(new PdfPen(Color.Black, 1), new PdfSolidBrush(_lightGray), summaryRect);

		var summaryY = currentY + 10;
		pdfPage.Graphics.DrawString("Summary", _subHeaderFont, new PdfSolidBrush(_primaryColor), new PointF(summaryX + 10, summaryY));

		summaryY += 25;

		// Draw summary items
		foreach (var item in summaryItems)
			if (!string.IsNullOrEmpty(item.Value))
			{
				summaryY += 15;
				DrawSummaryLine(pdfPage, item.Key, item.Value, summaryWidth, summaryX, summaryY);
			}

		// Draw grand total
		summaryY += 25;
		var grandTotalRect = new RectangleF(summaryX + 5, summaryY - 5, summaryWidth - 10, 25);
		pdfPage.Graphics.DrawRectangle(new PdfPen(_primaryColor, 2), new PdfSolidBrush(_primaryColor), grandTotalRect);
		pdfPage.Graphics.DrawString("Grand Total: ", new PdfStandardFont(PdfFontFamily.Helvetica, 12, PdfFontStyle.Bold),
			PdfBrushes.White, new PointF(summaryX + 10, summaryY));

		var grandTotalText = grandTotal.FormatIndianCurrency();
		var grandTotalFont = new PdfStandardFont(PdfFontFamily.Helvetica, 12, PdfFontStyle.Bold);
		var grandTotalSize = grandTotalFont.MeasureString(grandTotalText);

		pdfPage.Graphics.DrawString(grandTotalText, grandTotalFont,
			PdfBrushes.White, new PointF(summaryX + summaryWidth - grandTotalSize.Width - 15, summaryY));

		// Draw amount in words
		summaryY += 30;
		var amountInWords = grandTotal.ToNumericWords();
		if (string.IsNullOrEmpty(amountInWords))
			amountInWords = "Zero";
		amountInWords += " Rupees Only";

		var availableWidth = summaryWidth - 20;
		DrawWrappedText(pdfPage, amountInWords, _boldFont, new PdfSolidBrush(_primaryColor),
						new RectangleF(summaryX + 10, summaryY, availableWidth, 50),
						PdfTextAlignment.Left, ref summaryY);

		// Draw additional info if provided
		if (!string.IsNullOrEmpty(additionalInfo))
		{
			summaryY += 20;
			DrawSummaryLine(pdfPage, "Payment Mode: ", additionalInfo, summaryWidth, summaryX, summaryY);
		}

		return summaryRect.Height + summaryRect.Y + 20;
	}

	/// <summary>
	/// Draws wrapped text within specified bounds
	/// </summary>
	internal static void DrawWrappedText(PdfPage pdfPage, string text, PdfFont font, PdfBrush brush,
		RectangleF bounds, PdfTextAlignment alignment, ref float currentY)
	{
		const float lineSpacing = 15f;
		string[] words = text.Split(' ');
		string line = string.Empty;

		foreach (string word in words)
		{
			string testLine = string.IsNullOrEmpty(line) ? word : line + " " + word;
			SizeF testSize = font.MeasureString(testLine);

			if (testSize.Width <= bounds.Width)
				line = testLine;
			else
			{
				PdfStringFormat format = new() { Alignment = alignment };
				pdfPage.Graphics.DrawString(line, font, brush, new RectangleF(bounds.X, currentY, bounds.Width, bounds.Height), format);
				currentY += lineSpacing;
				line = word;
			}
		}

		if (!string.IsNullOrEmpty(line))
		{
			PdfStringFormat format = new() { Alignment = alignment };
			pdfPage.Graphics.DrawString(line, font, brush, new RectangleF(bounds.X, currentY, bounds.Width, bounds.Height), format);
			currentY += lineSpacing;
		}
	}

	/// <summary>
	/// Draws a summary line with label and value
	/// </summary>
	internal static void DrawSummaryLine(PdfPage pdfPage, string label, string value, float summaryWidth, float summaryX, float summaryY)
	{
		pdfPage.Graphics.DrawString(label, _normalFont, PdfBrushes.Black, new PointF(summaryX + 10, summaryY));
		pdfPage.Graphics.DrawString(value, _boldFont, new PdfSolidBrush(_secondaryColor),
			new PointF(summaryX + summaryWidth - _boldFont.MeasureString(value).Width - 15, summaryY));
	}

	/// <summary>
	/// Draws invoice details section with left and right column layout
	/// </summary>
	internal static float DrawInvoiceDetailsSection(PdfPage pdfPage, float currentY, string sectionTitle,
		Dictionary<string, string> leftColumnDetails, Dictionary<string, string> rightColumnDetails)
	{
		var detailsRect = new RectangleF(20, currentY, pdfPage.GetClientSize().Width - 40, 90);

		if (leftColumnDetails.Count > 3)
			detailsRect = new RectangleF(20, currentY, pdfPage.GetClientSize().Width - 40, 120);

		pdfPage.Graphics.DrawRectangle(new PdfPen(Color.Black, 1), detailsRect);

		var leftX = 30;
		var rightX = pdfPage.GetClientSize().Width / 2 + 20;
		var detailY = currentY + 10;

		// Section title
		pdfPage.Graphics.DrawString(sectionTitle, _subHeaderFont, new PdfSolidBrush(_primaryColor), new PointF(leftX, detailY));

		// Left column details
		detailY += 25;
		foreach (var detail in leftColumnDetails)
		{
			if (!string.IsNullOrEmpty(detail.Value))
			{
				pdfPage.Graphics.DrawString($"{detail.Key}: ", _normalFont, PdfBrushes.Black, new PointF(leftX, detailY));
				pdfPage.Graphics.DrawString(detail.Value, _boldFont, new PdfSolidBrush(_secondaryColor), new PointF(leftX + 60, detailY));
				detailY += 15;
			}
		}

		// Right column details
		detailY = currentY + 35;
		foreach (var detail in rightColumnDetails)
			if (!string.IsNullOrEmpty(detail.Value))
			{
				pdfPage.Graphics.DrawString($"{detail.Key}: ", _normalFont, PdfBrushes.Black, new PointF(rightX, detailY));

				// Handle longer text for cash discount
				var valueWidth = detail.Key.Contains("Cash Discount") ? 100 : 60;
				pdfPage.Graphics.DrawString(detail.Value, _boldFont, new PdfSolidBrush(_secondaryColor), new PointF(rightX + valueWidth, detailY));
				detailY += 15;
			}

		return detailsRect.Height + detailsRect.Y + 20;
	}

	/// <summary>
	/// Creates a new PDF document with A4 size and templates
	/// </summary>
	internal static (PdfDocument document, PdfPage page) CreateA4Document(string headerTitle)
	{
		var pdfDocument = new PdfDocument();
		var pdfPage = pdfDocument.Pages.Add();
		pdfDocument.PageSettings.Size = PdfPageSize.A4;

		pdfDocument.Template.Top = CreateHeader(pdfDocument, headerTitle);
		pdfDocument.Template.Bottom = CreateFooter(pdfDocument);

		return (pdfDocument, pdfPage);
	}

	/// <summary>
	/// Finalizes PDF document and returns as MemoryStream
	/// </summary>
	internal static MemoryStream FinalizePdfDocument(PdfDocument pdfDocument)
	{
		var stream = new MemoryStream();
		pdfDocument.Save(stream);
		pdfDocument.Close();
		return stream;
	}
}