CREATE TABLE [dbo].[SaleReturn]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(MAX) NOT NULL, 
    [CompanyId] INT NOT NULL,
    [LocationId] INT NOT NULL,
	[PartyId] INT NULL,
    [CustomerId] INT NULL, 
	[TransactionDateTime] DATETIME NOT NULL,
	[FinancialYearId] INT NOT NULL,
	[ItemsTotalAmount] MONEY NOT NULL DEFAULT 0,
    [OtherChargesPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[OtherChargesAmount] MONEY NOT NULL DEFAULT 0,
    [DiscountPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[DiscountAmount] MONEY NOT NULL DEFAULT 0,
	[RoundOffAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAmount] MONEY NOT NULL DEFAULT 0,
    [Cash] MONEY NOT NULL DEFAULT 0, 
    [Card] MONEY NOT NULL DEFAULT 0, 
    [UPI] MONEY NOT NULL DEFAULT 0, 
    [Credit] MONEY NOT NULL DEFAULT 0, 
	[Remarks] VARCHAR(MAX) NULL,
    [CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL,
    CONSTRAINT [FK_SaleReturn_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_SaleReturn_ToLedger] FOREIGN KEY ([PartyId]) REFERENCES [Ledger]([Id]), 
	CONSTRAINT [FK_SaleReturn_ToLocation] FOREIGN KEY (LocationId) REFERENCES [Location](Id), 
    CONSTRAINT [FK_SaleReturn_ToCustomer] FOREIGN KEY (CustomerId) REFERENCES [Customer](Id), 
    CONSTRAINT [FK_SaleReturn_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [dbo].[FinancialYear]([Id]),
    CONSTRAINT [FK_SaleReturn_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_SaleReturn_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
